language: java

matrix:
   include:
      - jdk: openjdk11
        env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"

# skip installation step
install: true

addons:
  sonarcloud:
    organization: "lorenzomorg-github"
    token:
      secure: "awbFNhFCF1yWr2HziMmBIeZGzkV+XWFuyRCbRTONy6qU6Kjgj1CSGbgfnTWWNMZAMNsydLYx0T/99SCtVPT7T/n4yex1uSvYAsD8vAE/AmhmLxMX8rOy8ZZ/T9G/CGl8ukcu0qrhQ89MN50Gmx7qJ3+2XYEtHUqWW3fiv8m7lWoCa4T9QxMG73sXxp+66nMZZR5SBcJTW30pXx9IjTDlQdcG3+gZOhO8bfoaGAohKLx/cqLovrxYUzjK5YVFPCPbKgUV+JcixEs7lq52Ajqr76UOJ/PtvlJ2BnGOaAql3xuHN9frrZk1mLotouxKo06HZyO4+/z8MhFIhk8IH4cjizoVnZ1hdKDVWGNw/Mm9SVmRc+purAid5ZnPV+cuhkbObfo1DMEibSJWAdnj1v1kMnGSakWh86ZRRcc6bqGrqnazreJGx56S8jY9Bgg1xLMqbmR2UKt431iE/yU1Rw9h/GRO2INddnzaBQmohHS/wa1AelZLeokJiSMJTy03oL8mV33sDxqduAJ6ISXK8e5Anea/3nhW45QsP4++l9rLdrw1Z1FG0Yi2AAmRRwyykf1pPETPI0MSf3UdLLJduc5DheI0bSUfIvdl9yHGNgk6KN/HPn4GdRYTBHgob/Ho3BfRwlMNfUVRxZLqVKMEfrqRwJ4kZF9R7pHeLlUh6nPZJhc="
    
script: 
  - cd attsd-spring-project 
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
   directories:
      - '$HOME/.m2'
      - '$HOME/.sonar/cache'
