language: java

matrix:
   include:
      - jdk: openjdk8
        env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
      #only on PR
      - jdk: openjdk9
      - os: osx
        osx_image: xcode10.1

# skip installation step
install: true

addons:
  sonarcloud:
    organization: "lorenzomorg-github"
    token:
      secure: "mocFWXCUOMbpeYf8ITyXVYs35hv21nyY/9Yw7xYrvIxWi1Z6rug2ypX4wN2XEco5yABQDSOI+6Q2anyxnZR5KFEdw3XVom7FLux3Xq04yVwKQuvNHpFCagM24ZiWabNyorp+heXMHIJfewsH5qnDMiZYBPqvuLLcv6U+/cGbdPoNsZurt1nFGbsgqla4R2bQyFpMU2w0V+8RxdBKu/vV4EuyVEFqHmh8+aXmtVHq1ROQpg7whe6o15wV0rj1VAXgzX+GAJJqsUsa2MmnbyihXxlro292tUyqZqFwbv2SnElblDuKsKxrIix1sHRN+5Y6sN2r0c4VGXyRt3T8eqPvTr+O1M7nyrMIavnrx14KOiNFGDVxru1t0oxIAK4OvRlMBTA/NvUdNw+HopGvPmcAlBKEGjWlOJtS2hPB5fzEIyljz+6Ym1FDFFLVH28VEr8p5mjW3bcFv4kJG+qcSuFjSVgzZxmQFg1e++/ko3aKFF20WuXew9zGAgAhXjSfoJyzXXZxop7PapNLkgbKtL+n11EVYVUEsczrX98QwNff6HwgSELGHPTk1zsOkA8+iXmGTXfzfkj/QbJTazYTG7au13an4qPzx+UOh0jqNz88R3k6pZSEixE+gIAOzMapXUJqxOdukBvzjmU9Mr8MQN3rEismzdNFnem8zTP5pkFmu4k="

script: 
  - cd attsd-spring-project 
  - mvn clean verify $ADDITIONAL_MAVEN_ARGS
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
   directories:
      - $HOME/.m2
