language: java

jdk: openjdk8
        
services:
  - docker
  - xvfb  

# skip installation step
install: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script: 
  - cd attsd-spring-project 
  - mvn clean verify -Pjacoco coveralls:report
  - mvn verify -PitTest
  - mvn verify -Pe2e

before_script:
  - export DISPLAY=:99.0

cache:
   directories:
      - $HOME/.m2
