language: java

sudo: false

# skip installation step
install: true
    
script: 
  - cd attsd-spring-project 
  - mvn clean verify -Pjacoco coveralls:report

cache:
   directories:
      - '$HOME/.m2'
