language: java

jdk: openjdk8
        
services:
  - docker

# skip installation step
install: true

script: 
  - cd attsd-spring-project 
  - mvn clean verify -Pjacoco coveralls:report
  - mvn verify -Pe2e


cache:
   directories:
      - $HOME/.m2
