language: java

jdk: openjdk8

env: DISPLAY=:99.0
        
services:
  - docker
  - xvfb

# skip installation step
install: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script: 
  - cd attsd-spring-project 
  - mvn clean verify -Pjacoco coveralls:report
  - mvn clean verify -Pit_tests
  - mvn clean verify -Pe2e_tests

cache:
   directories:
      - $HOME/.m2
